# Generated by Django 5.0 on 2024-04-23 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('review_tone', models.CharField(blank=True, choices=[('Professional and Informative', 'Professional and Informative'), ('Casual and Conversational', 'Casual and Conversational'), ('Critical and Honest', 'Critical and Honest'), ('Casual and Conservative', 'Casual and Conservative')], max_length=150, null=True)),
                ('product_name', models.TextField()),
                ('user_selected_words', models.CharField(default=None, max_length=200)),
                ('generated_review', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
