# Generated by Django 5.0 on 2024-04-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')])),
                ('review_tone', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.TextField(blank=True, null=True)),
                ('user_selected_words', models.CharField(default=None, max_length=455)),
                ('generated_review', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_aireview',
            },
        ),
    ]
