# Generated by Django 5.0 on 2024-06-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approve', 'Approve'), ('disapprove', 'Disapprove'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('star_rating', models.IntegerField()),
                ('review', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='', upload_to='uploaded_images/')),
                ('product_name', models.CharField(blank=True, default='', max_length=455, null=True)),
                ('domain', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reply_text', models.TextField(blank=True, null=True)),
                ('reply_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewFormDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('generate_button_color', models.CharField(blank=True, max_length=25)),
                ('generate_button_text_color', models.CharField(blank=True, max_length=25)),
                ('button_color', models.CharField(blank=True, max_length=25)),
                ('button_text_color', models.CharField(blank=True, max_length=25)),
                ('label_text_color', models.CharField(blank=True, max_length=25)),
                ('background_color', models.CharField(blank=True, max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Form Design',
                'verbose_name_plural': 'Review Form Design',
            },
        ),
        migrations.CreateModel(
            name='ReviewListDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('content_text_color', models.CharField(blank=True, max_length=25)),
                ('star_rating_color', models.CharField(blank=True, max_length=25)),
                ('reviewer_name_color', models.CharField(blank=True, max_length=25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review List Design',
                'verbose_name_plural': 'Review List Design',
            },
        ),
        migrations.CreateModel(
            name='ReviewSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Review Setting',
                'verbose_name_plural': 'Review Settings',
            },
        ),
    ]
