# Generated by Django 5.0 on 2024-06-13 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewformdesign',
            old_name='generate_button_color',
            new_name='generate_button',
        ),
        migrations.RenameField(
            model_name='reviewformdesign',
            old_name='generate_button_text_color',
            new_name='generate_button_text',
        ),
    ]
