# Generated by Django 5.0 on 2024-04-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='uploaded_images/'),
        ),
        migrations.AlterField(
            model_name='reviewformdesign',
            name='background_color',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='reviewformdesign',
            name='button_color',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='reviewformdesign',
            name='button_text_color',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='reviewformdesign',
            name='label_text_color',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='reviewlistdesign',
            name='content_text_color',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='reviewlistdesign',
            name='reviewer_name_color',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='reviewlistdesign',
            name='star_rating_color',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
