# Generated by Django 5.0 on 2024-04-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFormDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('button_color', models.CharField(blank=True, max_length=155)),
                ('button_text_color', models.CharField(blank=True, max_length=155)),
                ('label_text_color', models.CharField(blank=True, max_length=155)),
                ('background_color', models.CharField(blank=True, max_length=155)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review Form Design',
                'verbose_name_plural': 'Review Form Design',
            },
        ),
        migrations.CreateModel(
            name='ReviewListDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('content_text_color', models.CharField(blank=True, max_length=155)),
                ('star_rating_color', models.CharField(blank=True, max_length=155)),
                ('reviewer_name_color', models.CharField(blank=True, max_length=155)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review List Design',
                'verbose_name_plural': 'Review List Design',
            },
        ),
        migrations.DeleteModel(
            name='CSSProperty',
        ),
    ]
