# Generated by Django 5.0 on 2025-05-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reviewlistdesign',
            name='btn_border_radius',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Reviews Button Corners'),
        ),
        migrations.AlterField(
            model_name='reviewlistdesign',
            name='primary_btn_color',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Reviews Button Color'),
        ),
    ]
