# Generated by Django 5.0 on 2024-04-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='product_name',
            field=models.CharField(default='', max_length=455),
        ),
    ]
