# Generated by Django 4.2 on 2024-02-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='product_id',
            field=models.CharField(max_length=255),
        ),
    ]
