# Generated by Django 5.0 on 2024-09-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0002_remove_customer_password_remove_customer_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_img',
            field=models.ImageField(default='', null=True, upload_to='profile_images/'),
        ),
    ]
