# Generated by Django 5.0 on 2024-06-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0002_rename_generate_button_color_reviewformdesign_generate_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsettings',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
