# Generated by Django 5.0 on 2025-05-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0002_customer_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('features', models.CharField(blank=True, max_length=1000, null=True)),
                ('duration', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
