# Generated by Django 5.0 on 2024-04-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0002_reviewformdesign_reviewlistdesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=455, null=True),
        ),
    ]
