# Generated by Django 5.0 on 2024-01-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0002_alter_productreviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='image',
            field=models.ImageField(default='', upload_to='product_images/'),
        ),
    ]
