# Generated by Django 5.0 on 2024-04-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0002_alter_productreviews_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=455),
        ),
    ]
