# Generated by Django 5.0 on 2025-05-15 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0003_plans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.AddField(
            model_name='customer',
            name='plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_system.plans'),
        ),
    ]
