# Generated by Django 5.0 on 2024-05-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0003_alter_productreviews_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='status',
            field=models.CharField(choices=[('approve', 'Approve'), ('disapprove', 'Disapprove'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
