# Generated by Django 5.0 on 2025-05-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0004_alter_plans_options_customer_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='plan_id',
        ),
    ]
