# Generated by Django 5.0 on 2024-05-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0004_productreviews_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='auto_approve_reviews',
            field=models.BooleanField(default=False),
        ),
    ]
