# Generated by Django 5.0 on 2024-05-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0005_productreviews_auto_approve_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_reviews', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='productreviews',
            name='auto_approve_reviews',
        ),
    ]
