# Generated by Django 5.0 on 2024-05-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0006_appsettings_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppSettings',
        ),
        migrations.AddField(
            model_name='productreviews',
            name='auto_approve_reviews',
            field=models.BooleanField(default=False),
        ),
    ]
