# Generated by Django 5.0 on 2025-05-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0006_customer_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='plan_name',
        ),
    ]
