# Generated by Django 5.0 on 2024-05-02 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0007_delete_appsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviews',
            name='auto_approve_reviews',
        ),
    ]
