# Generated by Django 5.0 on 2025-05-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0007_remove_customer_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plan_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
