# Generated by Django 5.0 on 2025-05-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0009_alter_customer_date_end_alter_customer_date_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='plan_name',
        ),
    ]
