# Generated by Django 5.0 on 2025-06-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0010_remove_customer_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlistdesign',
            name='primary_button_position',
            field=models.CharField(blank=True, choices=[('Middle Left', 'Middle Left'), ('Middle Right', 'Middle Right'), ('Top Left', 'Top Left'), ('Top Middle', 'Top Middle'), ('Top Right', 'Top Right'), ('Bottom Left', 'Bottom Left'), ('Bottom Middle', 'Bottom Middle'), ('Bottom Right', 'Bottom Right')], default='Bottom Left', max_length=25, null=True, verbose_name='Reviews Button Position'),
        ),
    ]
