# Generated by Django 5.0 on 2024-05-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0012_alter_productreviews_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='reply_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
