# Generated by Django 5.0 on 2025-06-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0012_alter_reviewlistdesign_primary_button_position_sites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sites',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('collaborator', 'collaborator')], default='', max_length=25),
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_system.customer')),
            ],
            options={
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
            },
        ),
        migrations.CreateModel(
            name='CollaboratorInvitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('site_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_system.sites')),
            ],
            options={
                'verbose_name': 'Collaborator Invitation',
                'verbose_name_plural': 'Collaborator Invitations',
            },
        ),
    ]
