# Generated by Django 5.0 on 2025-06-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0013_rename_customer_id_sites_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='plan',
        ),
    ]
