# Generated by Django 5.0 on 2024-05-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0013_productreviews_reply_productreviews_reply_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='reply_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
