# Generated by Django 5.0 on 2025-06-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0014_remove_customer_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plan',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_system.plans', verbose_name='Plan Info'),
        ),
    ]
