# Generated by Django 5.0 on 2024-05-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0014_alter_productreviews_reply_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviews',
            old_name='reply_date',
            new_name='reply_created_at',
        ),
        migrations.RenameField(
            model_name='productreviews',
            old_name='reply',
            new_name='reply_text',
        ),
        migrations.AddField(
            model_name='productreviews',
            name='auto_approve',
            field=models.BooleanField(default=0),
        ),
    ]
