# Generated by Django 5.0 on 2025-06-16 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0015_customer_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlistdesign',
            name='btn_border_radius',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Reviews Button Corners'),
        ),
    ]
