# Generated by Django 5.0 on 2024-05-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0015_rename_reply_date_productreviews_reply_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='reply_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
