# Generated by Django 5.0 on 2025-06-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0016_alter_reviewlistdesign_btn_border_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratorinvitations',
            name='accepted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
