# Generated by Django 5.0 on 2024-05-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0017_alter_productreviews_reply_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='reply_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
