# Generated by Django 5.0 on 2025-06-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0017_alter_collaboratorinvitations_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratorinvitations',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
