# Generated by Django 5.0 on 2025-06-17 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0018_alter_collaboratorinvitations_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sites',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sites',
            name='plan',
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'owner'), ('collaborator', 'collaborator')], default='', max_length=25)),
                ('status', models.CharField(choices=[('invited', 'invited'), ('active', 'active'), ('removed', 'removed')], default='', max_length=25)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_system.customer')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_system.sites')),
            ],
            options={
                'verbose_name': 'Site User',
                'verbose_name_plural': 'Site Users',
            },
        ),
    ]
