# Generated by Django 5.0 on 2025-06-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0019_remove_sites_customer_remove_sites_plan_siteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='external_site_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
