# Generated by Django 5.0 on 2025-06-30 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0020_sites_external_site_id_sites_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trial', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('expired', 'expired')], max_length=30, null=True)),
                ('platform', models.CharField(blank=True, choices=[('wix', 'wix'), ('wordpress', 'wordpress')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_system.plans')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='review_system.sites')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_system.customer')),
            ],
            options={
                'verbose_name': 'Plan Subscription',
                'verbose_name_plural': 'Plan Subscriptions',
            },
        ),
    ]
