# Generated by Django 5.0 on 2025-07-01 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0021_plansubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_reviews',
            name='site',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='review_system.sites'),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='site',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='review_system.sites'),
        ),
        migrations.AddField(
            model_name='reviewformdesign',
            name='site',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='review_system.sites'),
        ),
        migrations.AddField(
            model_name='reviewlistdesign',
            name='site',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='review_system.sites'),
        ),
        migrations.AddField(
            model_name='reviewsettings',
            name='site',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='review_system.sites'),
        ),
    ]
