# Generated by Django 5.0 on 2025-07-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0022_google_reviews_site_productreviews_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscription',
            name='trial_ends_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
