# Generated by Django 5.0 on 2025-07-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0023_plansubscription_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
