# Generated by Django 5.0 on 2025-07-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0024_plansubscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='plan_price',
        ),
    ]
