# Generated by Django 5.0 on 2025-07-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_system', '0025_remove_customer_date_end_remove_customer_date_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewformdesign',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='reviewlistdesign',
            name='domain',
        ),
    ]
