# name: Django CI
 
# on:
#   push:
#     branches: [ "main" ]
 
 
# jobs:
#   build:
 
#     runs-on: self-hosted
#     strategy:
#       max-parallel: 4
#       matrix:
#         python3-version: [3.11.5]
 
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v3
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: Install Dependencies
#       run: |
#         pip3 install virtualenv
#         python3 -m virtualenv venvv
#         source venvv/bin/activate
#         pip3 install -r requirements.txt
